### ISSUE TITLE
App crashes while asking other permissions

### ISSUE THREAD

**Issue by sharathrajMindstack** [shounakmulay/Telephony#159]
Telephony permission forcing app to crash while asking other permission.

E/Parcel  (23087): Reading a NULL string not supported here.
D/AndroidRuntime(23087): Shutting down VM
E/AndroidRuntime(23087): FATAL EXCEPTION: main
E/AndroidRuntime(23087): Process: com.example.capizal_paygro, PID: 23087
E/AndroidRuntime(23087): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=0, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.example.capizal_paygro/io.flutter.embedding.android.FlutterFragmentActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(23087): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5439)
E/AndroidRuntime(23087): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5480)
E/AndroidRuntime(23087): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(23087): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(23087): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(23087): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2356)
E/AndroidRuntime(23087): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(23087): 	at android.os.Looper.loop(Looper.java:264)
E/AndroidRuntime(23087): 	at android.app.ActivityThread.main(ActivityThread.java:8315)
E/AndroidRuntime(23087): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23087): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
E/AndroidRuntime(23087): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
E/AndroidRuntime(23087): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(23087): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
E/AndroidRuntime(23087): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:272)
E/AndroidRuntime(23087): 	at com.shounakmulay.telephony.sms.SmsMethodCallHandler.onPermissionDenied(SmsMethodCallHandler.kt:383)
E/AndroidRuntime(23087): 	at com.shounakmulay.telephony.sms.SmsMethodCallHandler.onRequestPermissionsResult(SmsMethodCallHandler.kt:377)
E/AndroidRuntime(23087): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
E/AndroidRuntime(23087): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
E/AndroidRuntime(23087): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:752)
E/AndroidRuntime(23087): 	at io.flutter.embedding.android.FlutterFragment.onRequestPermissionsResult(FlutterFragment.java:901)
E/AndroidRuntime(23087): 	at io.flutter.embedding.android.FlutterFragmentActivity.onRequestPermissionsResult(FlutterFragmentActivity.java:549)
E/AndroidRuntime(23087): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8625)
E/AndroidRuntime(23087): 	at android.app.Activity.dispatchActivityResult(Activity.java:8473)
E/AndroidRuntime(23087): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5432)
E/AndroidRuntime(23087): 	... 11 more
I/Process (23087): Sending signal. PID: 23087 SIG: 9

**Comment by kaykhahima** [comment]
Experiencing the same issue. Did you get any resolution?

**Comment by hamsadev** [comment]
same issue.

**Comment by Zvirtuey** [comment]
same issue.
