### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getAllInboxSms on channel plugins.shounakmulay.com/foreground_sms_channel)

### ISSUE THREAD

**Issue by nikiforospertselis** [shounakmulay/Telephony#83]
My code 
```
 List<SmsMessage> recievedMessages = await telephony.getInboxSms(columns: [SmsColumn.ADDRESS, SmsColumn.DATE]);
```
I tried `flutter clean`, `flutter pub get`, `flutter pub cache repair`  but the error is the same.
I also tried to remove columns because _SmsColumn.ADDRESS_ & _SmsColumn.DATE_ are default

The error: 
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getAllInboxSms on channel plugins.shounakmulay.com/foreground_sms_channel)E/flutter (27137): 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
E/flutter (27137): <asynchronous suspension>
E/flutter (27137): #1      Telephony.getInboxSms (package:telephony/telephony.dart:177)
E/flutter (27137): <asynchronous suspension>
E/flutter (27137): #2      getLocation (package:bd_new/main.dart:303)
E/flutter (27137): <asynchronous suspension>
```

**Comment by shounakmulay** [comment]
Can you please give more details about when this happens.

Also this might be similar to #78 
Try out [v0.1.3](https://pub.dev/packages/telephony/versions/0.1.3) to see if that fixes your issue.
